# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NasdaqList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('last_sale', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('ipo', models.IntegerField()),
                ('sector', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('summary_quote', models.URLField()),
            ],
        ),
    ]
